---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: glestaris/xetex-dissertation-gr
    tag: latest
inputs:
  - name: dissertation
  - name: dissertation-version
  - name: ice-ci
outputs:
  - name: dissertation-pdf
run:
  user: root
  path: ice-ci/pipeline/tasks/build-dissertation.sh
