---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: "1.7"
inputs:
  - name: ice-ci
  - name: clique
run:
  path: ice-ci/pipeline/tasks/run-clique-tests.sh
