groups:
  - name: main
    jobs:
      - run-ice-unit-tests
      - run-ice-integration-tests
      - build-ice-docker-image

resources:
  - name: ice
    type: git
    source:
      uri: https://github.com/ice-stuff/ice
      branch: wip-integrate-agent

  - name: ice-ci
    type: git
    source:
      uri: https://github.com/ice-stuff/ice-ci
      branch: master

  - name: ice-docker-image
    type: docker-image
    source:
      repository: glestaris/ice-ci
      tag: latest
      username: {{DockerHubUsername}}
      password: {{DockerHubPassword}}

jobs:
  - name: build-ice-docker-image
    public: true
    plan:
      - get: ice
      - get: ice-ci
      - put: ice-docker-image
        params:
          build: .
          dockerfile: ice-ci/dockerfiles/ice-ci/Dockerfile

  - name: run-ice-unit-tests
    public: true
    plan:
      - get: ice
        trigger: true
      - get: ice-ci
      - task: run-ice-unit-tests
        privileged: true
        file: ice-ci/pipeline/tasks/run-ice-unit-tests.yml

  - name: run-ice-integration-tests
    public: true
    plan:
      - get: ice
        trigger: true
        passed:
          - run-ice-unit-tests
      - get: ice-ci
        passed:
          - run-ice-unit-tests
      - task: run-ice-integration-tests
        privileged: true
        file: ice-ci/pipeline/tasks/run-ice-integration-tests.yml
