groups:
  - name: main
    jobs:
      - run-ice-unit-tests
      - run-ice-integration-tests
      - run-clique-tests
      - deploy-ice-registry
  - name: ci-images
    jobs:
      - build-ice-ci-image
      - build-ice-agent-ci-image

resources:
  - name: ice
    type: git
    source:
      uri: https://github.com/ice-stuff/ice
      branch: master

  - name: ice-registry-cf
    type: git
    source:
      uri: https://github.com/ice-stuff/ice-registry-cf
      branch: master

  - name: clique
    type: git
    source:
      uri: https://github.com/ice-stuff/clique
      branch: master

  - name: ice-agent
    type: git
    source:
      uri: https://github.com/ice-stuff/ice-agent
      branch: master

  - name: ice-ci
    type: git
    source:
      uri: https://github.com/ice-stuff/ice-ci
      branch: master

  - name: ice-ci-image
    type: docker-image
    source:
      repository: glestaris/ice-ci
      tag: latest
      username: {{DockerHubUsername}}
      password: {{DockerHubPassword}}

  - name: ice-agent-ci-image
    type: docker-image
    source:
      repository: glestaris/ice-agent-ci
      tag: latest
      username: {{DockerHubUsername}}
      password: {{DockerHubPassword}}

  - name: ice-registry-cf-deployment
    type: cf
    source:
      api: https://api.run.pivotal.io
      username: {{PWSUsername}}
      password: {{PWSPassword}}
      organization: glestaris-pivotal-org
      space: development
      skip_cert_check: false

jobs:
  - name: build-ice-ci-image
    public: true
    plan:
      - get: ice-ci
      - put: ice-ci-image
        params:
          build: .
          dockerfile: ice-ci/dockerfiles/ice-ci/Dockerfile

  - name: build-ice-agent-ci-image
    public: true
    plan:
      - get: ice-agent
      - put: ice-agent-ci-image
        params:
          build: .
          dockerfile: ice-agent/Dockerfile

  - name: run-ice-unit-tests
    public: true
    plan:
      - get: ice
        trigger: true
      - get: ice-ci
      - task: run-ice-unit-tests
        privileged: true
        file: ice-ci/pipeline/tasks/run-ice-unit-tests.yml

  - name: run-ice-integration-tests
    public: true
    plan:
      - get: ice
        trigger: true
        passed:
          - run-ice-unit-tests
      - get: ice-ci
      - task: run-ice-integration-tests
        privileged: true
        file: ice-ci/pipeline/tasks/run-ice-integration-tests.yml

  - name: deploy-ice-registry
    public: true
    serial: true
    plan:
      - get: ice
        passed:
          - run-ice-integration-tests
      - get: ice-ci
      - get: ice-registry-cf
      - task: setup-ice-registry-cf-directory
        file: ice-ci/pipeline/tasks/setup-ice-registry-cf-directory.yml
      - put: ice-registry-cf-deployment
        params:
          manifest: ice-cf/manifest.yml
          current_app_name: ice_registry
          path: ice-cf

  - name: run-clique-tests
    public: true
    plan:
      - get: clique
        trigger: true
      - get: ice-ci
      - task: run-clique-tests
        privileged: true
        file: ice-ci/pipeline/tasks/run-clique-tests.yml
