#!/bin/bash
set -e
BASE_PATH=$(cd $(dirname $BASH_SOURCE)/../..; pwd)
source $BASE_PATH/configuration

# Dockerhub secrets
echo "DockerHubUsername: \""$(lpass show --username $LASTPASS_DOCKERHUB_ID)"\""
echo "DockerHubPassword: \""$(lpass show --password $LASTPASS_DOCKERHUB_ID)"\""

# PWS secrets
echo "PWSUsername: \""$(lpass show --username $LASTPASS_PWS_ID)"\""
echo "PWSPassword: \""$(lpass show --password $LASTPASS_PWS_ID)"\""

# Dissertation bucket S3 creds
eval $(lpass show --notes $LASTPASS_S3CREDS_ID)
echo "DissertationS3AWSAccessKey: \"$aws_access_key\""
echo "DissertationS3AWSSecretKey: \"$aws_secret_key\""

# Bitbucket SSH key
echo "BitbucketPrivateKey: |"
lpass show --notes $LASTPASS_BITBUCKETSSHKEY_ID | sed -e 's/^/  /g'
