#!/bin/bash
set -e
BASE_PATH=$(cd $(dirname $BASH_SOURCE)/../..; pwd)
source $BASE_PATH/configuration

# Dockerhub secrets
echo "DockerHubUsername: \""$(lpass show --username $LASTPASS_DOCKERHUB_ID)"\""
echo "DockerHubPassword: \""$(lpass show --password $LASTPASS_DOCKERHUB_ID)"\""
