concourse-db:
  image: postgres:9.5.7
  volumes: ["./data:/database"]
  environment:
    POSTGRES_DB: concourse
    POSTGRES_USER: CHANGE_ME
    POSTGRES_PASSWORD: CHANGE_ME
    PGDATA: /database

concourse-web:
  image: concourse/concourse:3.3.3
  links: [concourse-db]
  command: web
  ports: ["127.0.0.1:8080:8080"]
  volumes: ["./keys/web:/concourse-keys"]
  environment:
    CONCOURSE_LOG_DB_QUERIES: 1
    CONCOURSE_BASIC_AUTH_USERNAME: CHANGE_ME
    CONCOURSE_BASIC_AUTH_PASSWORD: CHANGE_ME
    CONCOURSE_EXTERNAL_URL: https://ice-ci.g-php.com/
    CONCOURSE_POSTGRES_DATA_SOURCE: |-
      postgres://CHANGE_ME:CHANGE_ME@concourse-db:5432/concourse?sslmode=disable

concourse-worker:
  image: concourse/concourse:3.3.3
  privileged: true
  links: [concourse-web]
  command: worker
  volumes: ["./keys/worker:/concourse-keys"]
  environment:
    CONCOURSE_TSA_HOST: concourse-web

concourse-nginx:
  image: nginx:1.13.3
  ports: ["80:80", "443:443"]
  links: [concourse-web]
  volumes: ["./nginx.conf:/etc/nginx/nginx.conf", "./certs:/etc/certs"]
