concourse-db:
  image: postgres:9.5
  volumes: ["./data:/database"]
  environment:
    POSTGRES_DB: concourse
    POSTGRES_USER: concourse
    POSTGRES_PASSWORD: 34p0stgressPa$$w0rd87
    PGDATA: /database

concourse-web:
  image: concourse/concourse
  links: [concourse-db]
  command: web
  ports: ["8080:8080"]
  volumes: ["./keys/web:/concourse-keys"]
  environment:
    CONCOURSE_LOG_DB_QUERIES: 1
    CONCOURSE_BASIC_AUTH_USERNAME: george
    CONCOURSE_BASIC_AUTH_PASSWORD: georgeConcourse12
    CONCOURSE_EXTERNAL_URL: http://snf-726814.vm.okeanos.grnet.gr/
    CONCOURSE_POSTGRES_DATA_SOURCE: |-
      postgres://concourse:34p0stgressPa$$w0rd87@concourse-db:5432/concourse?sslmode=disable

concourse-worker:
  image: concourse/concourse
  privileged: true
  links: [concourse-web]
  command: worker
  volumes: ["./keys/worker:/concourse-keys"]
  environment:
    CONCOURSE_TSA_HOST: concourse-web

concourse-nginx:
  image: nginx:1.11
  links: [concourse-web]
  ports: ["80:80"]
  volumes: ["/usr/local/concourse/nginx.conf:/etc/nginx/nginx.conf"]
